test: add healthcheck to e2e ci job
fix: invalid curl string

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -383,6 +383,13 @@ jobs:
             source ~/.asdf/asdf.sh
             pushd app
             NO_MATHJAX=true yarn start AS_CYPRESS & yarn wait-on http://localhost:3004
+            status_code=$(curl --write-out %{http_code} --silent --output /dev/null http://localhost:3004/health)
+            if [[ "$status_code" -ne 200 ]] ; then
+              echo "healthcheck failed: database is not available or is in recovery mode"
+              exit 1
+            else
+              echo "healthcheck passed"
+            fi
             yarn test:e2e-snapshots
             popd
       - run:
