check schema consistency

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -27,7 +27,8 @@ jobs:
             [[ -d ~/.asdf ]] || git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.4
             pushd ~/.asdf && git checkout v0.7.4 && popd
             echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc
-            source ~/.asdf/asdf.sh
+            echo -e '\nexport BASH_ENV="~/.asdf/asdf.sh"' >> ~/.bashrc
+            source ~/.bashrc
             cat .tool-versions | cut -f 1 -d ' ' | xargs -n 1 asdf plugin-add || true
             asdf plugin-update --all
             bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
@@ -45,10 +46,10 @@ jobs:
           keys:
             - yarn-packages-{{ checksum "app/yarn.lock" }}
       - run:
-          name: Install Dependencies
+          name: Install Yarn Dependencies
           command: |
-            pushd app || exit 1
-            source ~/.asdf/asdf.sh
+            source ~/.bashrc
+            pushd app
             yarn install --frozen-lockfile
             popd
       - save_cache:
@@ -56,11 +57,34 @@ jobs:
           key: yarn-packages-{{ checksum "app/yarn.lock" }}
           paths:
             - ~/.cache/yarn
+      - run:
+          name: Configure Cpan
+          command: |
+            echo | cpan # accept cpan defaults
+      - restore_cache:
+          name: Restore Cpan Package Cache
+          keys:
+            - cpanm-packages-b-{{ checksum "schema/cpanfile" }}
+      - run:
+          name: Install Cpan Dependencies
+          command: |
+            source ~/.bashrc # load perl config (just written by cpan) & asdf
+            cat .tool-versions | xargs -n2 asdf global # make this project's versions global
+            pushd schema
+            make dev_install
+            popd
+      - save_cache:
+          name: Save Cpan Package Cache
+          key: cpanm-packages-b-{{ checksum "schema/cpanfile" }}
+          paths:
+            - ~/perl5
       - persist_to_workspace:
           root: ~/
           paths:
             - .asdf
+            - .bashrc
             - cas-ciip-portal
+            - perl5
 
   lint:
     machine:
@@ -73,7 +97,7 @@ jobs:
           name: Run XO via Yarn
           command: |
             source ~/.asdf/asdf.sh
-            yarn lint || true # TODO: need to clean up linter errors
+            yarn format || true # TODO: need to clean up linter errors
       - run:
           name: Check if there is some unformatted code
           command: git diff --exit-code || (echo 'These files are not formatted correctly. Did you forget to \"yarn format\"?' && false)
@@ -118,15 +142,57 @@ jobs:
       - attach_workspace:
           at: ~/
       - run:
+          name: start postgres
+          command: |
+            source ~/.bashrc
+            pg_ctl start
+            createdb `whoami`
+            createdb ggircs_dev
+      - run:
+          name: deploy cas-ggircs schema (SHOULD NOT NEED THIS)
+          command: |
+            source ~/.bashrc
+            cat .tool-versions | xargs -n2 asdf global # make this project's versions global
+            git clone https://github.com/bcgov/cas-ggircs.git ~/cas-ggircs --branch master
+            pushd ~/cas-ggircs
+            sqitch deploy
+            popd
+      - run:
           name: deploy schema
           command: |
-            source ~/.asdf/asdf.sh
-            pg_ctl start
-            createdb ggircs_dev
+            source ~/.bashrc
             pushd schema
             sqitch deploy
             sqitch verify
             popd
+      - run:
+          name: regenerate schema via introspection
+          command: |
+            source ~/.bashrc
+            pushd app
+            yarn build:schema
+            popd
+      - run:
+          name: check for inconsistency between schema ddl & graphql
+          command: git diff --exit-code || (echo 'The contents of the `schema` folder are out of sync with `app/server/schema.graphql`. Did you forget to \"yarn build:relay\"?' && false)
+      - run:
+          name: redeploy schema
+          command: |
+            source ~/.bashrc
+            pushd schema
+            sqitch rebase
+            sqitch verify
+            popd
+      - run:
+          name: regenerate schema via introspection
+          command: |
+            source ~/.bashrc
+            pushd app
+            yarn build:schema
+            popd
+      - run:
+          name: check for inconsistency between schema ddl & graphql
+          command: git diff --exit-code || (echo 'The contents of the `schema` folder are out of sync with `app/server/schema.graphql`. Did you forget to \"yarn build:relay\"?' && false)
 
   test-local-cluster:
     executor: redhat-openshift/machine-for-local-cluster
@@ -167,7 +233,7 @@ jobs:
           command: make install-prod
           name: Deploy to prod
 
-  openshift-lint:
+  pathfinder_lint:
     executor: redhat-openshift/default
     steps:
       - checkout
@@ -185,7 +251,7 @@ jobs:
           command: make lint
           name: Lint the openshift yaml
 
-  configure:
+  pathfinder_configure:
     executor: redhat-openshift/default
     steps:
       - checkout
@@ -203,7 +269,7 @@ jobs:
           command: make configure
           name: Configure imagestream to point at the current SHA1
 
-  build_schema:
+  pathfinder_build_schema:
     executor: redhat-openshift/default
     steps:
       - checkout
@@ -221,7 +287,7 @@ jobs:
           command: make build_schema
           name: Build image on the remote cluster
 
-  build_app:
+  pathfinder_build_app:
     executor: redhat-openshift/default
     steps:
       - checkout
@@ -256,7 +322,7 @@ workflows:
       - schema:
           requires:
             - tools
-      - openshift-lint:
+      - pathfinder_lint:
           requires:
             - audit
             - lint
@@ -266,24 +332,24 @@ workflows:
           filters:
             branches:
               ignore: /^shipit-deploy\/.*/
-      - configure:
+      - pathfinder_configure:
           context: cas-pipeline
           requires:
-            - openshift-lint
+            - pathfinder_lint
           filters:
             branches:
               ignore: /^shipit-deploy\/.*/
-      - build_schema:
+      - pathfinder_build_schema:
           context: cas-pipeline
           requires:
-            - configure
+            - pathfinder_configure
           filters:
             branches:
               ignore: /^shipit-deploy\/.*/
-      - build_app:
+      - pathfinder_build_app:
           context: cas-pipeline
           requires:
-            - configure
+            - pathfinder_configure
           filters:
             branches:
               ignore: /^shipit-deploy\/.*/
