feat: circleci job for smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -408,7 +408,59 @@ jobs:
             yarn start AS_CYPRESS & yarn wait-on http://localhost:3004
             yarn test:e2e-with-mocks
             popd
-
+  smoke:
+    machine:
+      image: ubuntu-1604:201903-01
+    working_directory: ~/cas-ciip-portal
+    steps:
+      - run:
+          name: install K6
+          command: |
+            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C5AD17C747E3415A3642D57D77C6C491D6AC1D69
+            echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
+            sudo apt-get update
+            sudo apt-get install k6
+      - attach_workspace:
+          at: ~/
+      - run:
+          name: "Checkout Submodules"
+          command: |
+            git submodule update --init
+      - run:
+          name: start postgres
+          command: |
+            source ~/.bashrc
+            pg_ctl start
+            createdb `whoami`
+      - run:
+          name: deploy schemas and data
+          command: |
+            source ~/.bashrc
+            ./.bin/deploy-data.sh -dev
+            pushd test_helper_schema
+            SQITCH_TARGET="ciip_portal_dev" sqitch deploy
+            popd
+            pushd mocks_schema
+            SQITCH_TARGET="ciip_portal_dev" sqitch deploy
+            popd
+      - run:
+          name: run smoke test with k6
+          command: |
+            source ~/.bashrc
+            pushd app
+            status_code=$(curl --write-out %{http_code} --silent --output /dev/null http://localhost:3004/health)
+            if [[ "$status_code" -ne 200 ]] ; then
+              echo "healthcheck failed: database is not available or is in recovery mode"
+              exit 1
+            else
+              echo "healthcheck passed"
+            fi
+            popd
+            pushd app/tests/perf
+            export
+            psql -d ciip_portal_dev -f mutations-setup.sql
+            node test-guest.js && node test-admin.js && node test-reporter.js && k6 run k6-mutations.js
+            popd
   sqitch-plan-ends-with-tag:
     machine:
       image: ubuntu-1604:201903-01
@@ -459,6 +511,9 @@ workflows:
           requires:
             - tools
       - e2e-snapshots:
+          requires:
+            - compile
+      - smoke:
           requires:
             - compile
             - unit
